# steps:
#   - name: "gcr.io/cloud-builders/git"
#     args: ["clone", "https://github.com/your-org/your-repo.git"]

#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/$PROJECT_ID/app:$COMMIT_SHA", "."]

#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/$PROJECT_ID/app:$COMMIT_SHA"]

#   - name: "gcr.io/cloud-builders/gke-deploy"
#     args:
#       - run
#       - --filename=k8s/
#       - --image=gcr.io/$PROJECT_ID/app:$COMMIT_SHA
#       - --location=us-central1
#       - --cluster=production-cluster

# options:
#   logging: CLOUD_LOGGING_ONLY
#   machineType: "E2_HIGHCPU_8"

# timeout: "1200s"

# substitutions:
#   _ENVIRONMENT: "production"
#   _REGION: "us-central1"
